x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    shm_size: 256mb
    networks:
      - internal
    logging: *default-logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d ${POSTGRES__DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS__PASSWORD}"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - internal
    logging: *default-logging
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS__PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    image: ghcr.io/dofer998/tribute-donation-telegram-bot:latest
    pull_policy: always
    init: true
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal
      - proxy
    restart: unless-stopped
    logging: *default-logging

volumes:
  postgres_data:
  redis_data:

networks:
  internal:
  proxy:
    external: true
    name: proxy
