"""initial

Revision ID: 432da6cbf8c4
Revises: 
Create Date: 2026-05-07 21:57:06.800947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '432da6cbf8c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tribute_donation_request_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_created_at'), 'donations', ['created_at'], unique=False)
    op.create_index(op.f('ix_donations_currency'), 'donations', ['currency'], unique=False)
    op.create_index(op.f('ix_donations_is_anonymous'), 'donations', ['is_anonymous'], unique=False)
    op.create_index(op.f('ix_donations_telegram_user_id'), 'donations', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_donations_tribute_donation_request_id'), 'donations', ['tribute_donation_request_id'], unique=True)
    op.create_table('fundraisers',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_amount', sa.BigInteger(), nullable=False),
    sa.Column('current_amount', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('count_donations_from', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('channel_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraisers_created_at'), 'fundraisers', ['created_at'], unique=False)
    op.create_index(op.f('ix_fundraisers_status'), 'fundraisers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundraisers_status'), table_name='fundraisers')
    op.drop_index(op.f('ix_fundraisers_created_at'), table_name='fundraisers')
    op.drop_table('fundraisers')
    op.drop_index(op.f('ix_donations_tribute_donation_request_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_telegram_user_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_is_anonymous'), table_name='donations')
    op.drop_index(op.f('ix_donations_currency'), table_name='donations')
    op.drop_index(op.f('ix_donations_created_at'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
