"""add fundraiser topic_id

Revision ID: f4d44970a477
Revises: 432da6cbf8c4
Create Date: 2026-05-08 14:25:11.141205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4d44970a477'
down_revision: Union[str, Sequence[str], None] = '432da6cbf8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundraisers', sa.Column('topic_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundraisers', 'topic_id')
    # ### end Alembic commands ###
